### PR TITLE
Added DummyQueryCollection for easier mocking of HttpRequests

### PR DESCRIPTION
**Pull request by DavidAtImpactCubed**
To make it easier to mock Http requests with query parameters, I created a simple wrapper around a dictionary which can be used instead of a QueryCollection.

I figured I might as well share!

### CODE REVIEW

**Comment by riezebosch** [comment]
Thanks! Looking through it right now.

**Comment by riezebosch** [comment]
I fiddled a little and came to this solution:

```c#
public static class QueryCollectionExtensions
{
    public static IQueryCollection AsQuery(this IDictionary<string, string> items) => 
        new QueryCollection(items.ToDictionary(x => x.Key, x => (StringValues)x.Value));
}

public class DummyHttpRequestTests
{
    [Fact]
    public static void QueryCollection()
    {
        var request = new DummyHttpRequest
        {
            Query = new QueryCollection(new Dictionary<string, StringValues> { ["first"] = "Jane" })
        };

        request
            .Query["first"]
            .Should()
            .BeEquivalentTo("Jane");
    }
    
    [Fact]
    public static void FromDictionary()
    {
        var request = new DummyHttpRequest
        {
            Query = new Dictionary<string, string> { ["first"] = "Jane" }.AsQuery()
        };

        request
            .Query["first"]
            .Should()
            .BeEquivalentTo("Jane");
    }
}
```

My observation is the default query collection already supports initialization from a `Dictionary<string, StringValues>` and you can simplify this construction a little with an extension method. Would that also make sense to you?

**Comment by riezebosch** [comment]
merged, thanks!

**Comment by DavidAtImpactCubed** [comment]
Awesome, yes it makes sense. Sorry for the slow reply.

**Comment by DavidAtImpactCubed** [comment]
NB - I also made a change to the readme, which isn't updated:

New: Now you can use a DummyQueryCollection to mock the url query:

var request = new DummyHttpRequest
{
    Query = new DummyQueryCollection
    {
        ["firstname"] = "Jane",
        ["lastname"] = "Doe"
    }
};

**Pull request closed without merging**
